export const mockData = [
    {
        "id": "1kz6md3",
        "title": "We have a date!",
        "body": "",
        "numUpvotes": 20212,
        "dateCreated": "Fri May 30 2025 08:08:09 GMT-0700 (Pacific Daylight Time)",
        "upTime": 3,
        "subreddit": "KingOfTheHill",
        "subredditId": "t5_2s6dm",
        "author": "theREAL_BalloonBoy09",
        "comments": [],
        "img": "https://preview.redd.it/9hc769o5qx3f1.jpeg?auto=webp&s=11e445a5dab0e1375bb247dfe4e98dbfbde0b7db"
    },
    {
        "id": "1kz5xgo",
        "title": "This is how plants breathe: a microscopic close-up of a single stoma on a boat lily leaf.",
        "body": "",
        "numUpvotes": 25109,
        "dateCreated": "Fri May 30 2025 07:40:16 GMT-0700 (Pacific Daylight Time)",
        "upTime": 4,
        "subreddit": "Damnthatsinteresting",
        "subredditId": "t5_2xxyj",
        "author": "TRIPYXEN",
        "comments": [],
        "img": "https://external-preview.redd.it/eDUxc3FqY3preDNmMVRooBfPateepzDsarKrvXSx5EsNtzJyhch4WaMHL2cU.png?format=pjpg&auto=webp&s=8b80c096f0f15a1864093b7f6d6bc4e8c1af2134"
    },
    {
        "id": "1kyyvgd",
        "title": "Name the game that got you like this",
        "body": "",
        "numUpvotes": 28043,
        "dateCreated": "Fri May 30 2025 01:18:17 GMT-0700 (Pacific Daylight Time)",
        "upTime": 10,
        "subreddit": "Steam",
        "subredditId": "t5_2qwis",
        "author": "bijelo123",
        "comments": [],
        "img": "https://preview.redd.it/w2re7q71pv3f1.jpeg?auto=webp&s=937d13b6d6a05585166a0330a0dd330b3e5a7f19"
    },
    {
        "id": "1kz175l",
        "title": "Bernie Sanders blames election loss on Kamala Harris listening to billionaires over the working class",
        "body": "",
        "numUpvotes": 41551,
        "dateCreated": "Fri May 30 2025 03:52:07 GMT-0700 (Pacific Daylight Time)",
        "upTime": 7,
        "subreddit": "politics",
        "subredditId": "t5_2cneq",
        "author": "The__Illuminaughty",
        "comments": [],
        "img": "https://external-preview.redd.it/9UE1__JGBPBy4Zb6kHFcoI9SRqEdUDIJo3weBYTEJ3s.jpg?auto=webp&s=7673b3b1fff05c2181b0f865d465ec1463116f9e"
    },
    {
        "id": "1kyydm2",
        "title": "Draw a B on your keyboard.Let's see what autocorrect is up to.",
        "body": "",
        "numUpvotes": 2472,
        "dateCreated": "Fri May 30 2025 00:43:07 GMT-0700 (Pacific Daylight Time)",
        "upTime": 11,
        "subreddit": "teenagers",
        "subredditId": "t5_2rjli",
        "author": "Stunning-Weakness257",
        "comments": [],
        "img": "https://preview.redd.it/fiye3l9riv3f1.jpeg?auto=webp&s=c45aaca5f68494186dffaad40c02c3f69a83ce49"
    },
    {
        "id": "1kz6slj",
        "title": "Wedding DJ's smooth transition",
        "body": "",
        "numUpvotes": 15172,
        "dateCreated": "Fri May 30 2025 08:15:07 GMT-0700 (Pacific Daylight Time)",
        "upTime": 3,
        "subreddit": "oddlysatisfying",
        "subredditId": "t5_2x93b",
        "author": "HereWeFuckingGooo",
        "comments": [],
        "img": "https://external-preview.redd.it/MmxjcmgxY2VweDNmMWBoAq8lcpTFZLtb9D-t2qK9yd1WtAn6C3phj8LQ_DBK.png?format=pjpg&auto=webp&s=f6525449e0af52fe3fb2c8d361762db46752403c"
    },
    {
        "id": "1kz762l",
        "title": "Taylor has gained back the rights to all of her music again",
        "body": "I mean the kind of achievement that would secure Taylor's legend status in the future. Anything about her touring success, streaming success, selling success, cutural impact, critical acclaim… can be considered. Is it her 4th win for Album of The Year at Grammy? Is it “The Eras Tour” — the highest grossing tour of all time? Or anything else?",
        "numUpvotes": 15658,
        "dateCreated": "Fri May 30 2025 08:30:09 GMT-0700 (Pacific Daylight Time)",
        "upTime": 3,
        "subreddit": "TaylorSwift",
        "subredditId": "t5_2rlwe",
        "author": "maydeletelater",
        "comments": [],
        "img": ""
    },
    {
        "id": "1kz87j6",
        "title": "The Moth - Gator Days (OC)",
        "body": "",
        "numUpvotes": 12030,
        "dateCreated": "Fri May 30 2025 09:11:32 GMT-0700 (Pacific Daylight Time)",
        "upTime": 2,
        "subreddit": "comics",
        "subredditId": "t5_2qh0s",
        "author": "FieldExplores",
        "comments": [],
        "img": "https://preview.redd.it/9ms3obze1y3f1.png?auto=webp&s=5c56e488045ddc7cf4014bfaff4843d719787b0b"
    },
    {
        "id": "1kz4d9v",
        "title": "What's up for today, Neddy?",
        "body": "",
        "numUpvotes": 37086,
        "dateCreated": "Fri May 30 2025 06:34:38 GMT-0700 (Pacific Daylight Time)",
        "upTime": 5,
        "subreddit": "lego",
        "subredditId": "t5_2qhm7",
        "author": "touthomme",
        "comments": [],
        "img": "https://external-preview.redd.it/eGtxMGx2NGg5eDNmMYyeQ3zGB9v6kHbGKPmip8aL6sY4pxL0zUr35oQ560-5.png?format=pjpg&auto=webp&s=4ebb443e9f9e5a242cad93174ff0d5e401aa53a5"
    },
    {
        "id": "1kz44r0",
        "title": "Why aren’t the employers arrested too?",
        "body": "https://bsky.app/profile/piperformissouri.bsky.social/post/3lqd3dsxxes2q",
        "numUpvotes": 21834,
        "dateCreated": "Fri May 30 2025 06:23:58 GMT-0700 (Pacific Daylight Time)",
        "upTime": 5,
        "subreddit": "BlueskySkeets",
        "subredditId": "t5_90wgu7",
        "author": "IthinkIknowwhothatis",
        "comments": [],
        "img": "https://preview.redd.it/woles2ik7x3f1.jpeg?auto=webp&s=fa391c031c3af899a197e306ffd0df8de005a648"
    },
    {
        "id": "1kypj8h",
        "title": "The Asshole escaped outside and bit me when I got him back in",
        "body": "",
        "numUpvotes": 49339,
        "dateCreated": "Thu May 29 2025 16:31:39 GMT-0700 (Pacific Daylight Time)",
        "upTime": 19,
        "subreddit": "CatsAreAssholes",
        "subredditId": "t5_2zexl",
        "author": "AzraelKhaine",
        "comments": [],
        "img": ""
    },
    {
        "id": "1kz6jb9",
        "title": "Trump Taps Palantir to Create Master Database on Every American. Trump’s dystopian plan is already underway.",
        "body": "",
        "numUpvotes": 10981,
        "dateCreated": "Fri May 30 2025 08:04:46 GMT-0700 (Pacific Daylight Time)",
        "upTime": 3,
        "subreddit": "technology",
        "subredditId": "t5_2qh16",
        "author": "Aggravating_Money992",
        "comments": [],
        "img": "https://external-preview.redd.it/vLGAlhq-VRzUF64lBwvlST60PQ5xg-fld-TQwm9B2r0.jpg?auto=webp&s=552f1ad02bf1d7a8cef22a8280d2f74e3d4b958f"
    },
    {
        "id": "1kz0vxp",
        "title": "What's The Best Movie That You're Sure 90% Of This Sub Hasn't Seen?",
        "body": "Looking for some underrated films! \n\nMy personal pick is \"Coherence\" (2013). One of the films that blows your mind once you realize what's happening. Even more impressive that it was shot in 5 nights with no script (about 80% of the dialogue is ad-libbed) which makes the whole movie even more grounded and realistic. Phenomenal film, and go watch it as blindly as you can, its a one of a kind experience.",
        "numUpvotes": 2874,
        "dateCreated": "Fri May 30 2025 03:33:09 GMT-0700 (Pacific Daylight Time)",
        "upTime": 8,
        "subreddit": "movies",
        "subredditId": "t5_2qh3s",
        "author": "Rhye5",
        "comments": [],
        "img": ""
    },
    {
        "id": "1kz0kbw",
        "title": "[OC] WORLDWIDE GIVEAWAY! Enter for a chance to win a FAFNIR DICE VAULT![MOD APPROVED]",
        "body": "Limited time **DISCOUNT CODE**! Use code '**REDDIT3**' when buying a Dice Vault or a set of dice from my website for **10% off!** This code is good for a week. [www.magnicraftworks.com](https://magnicraftworks.com/) We add new dice sets weekly!",
        "numUpvotes": 2813,
        "dateCreated": "Fri May 30 2025 03:12:46 GMT-0700 (Pacific Daylight Time)",
        "upTime": 8,
        "subreddit": "DnD",
        "subredditId": "t5_2r9ei",
        "author": "120mmfilms",
        "comments": [],
        "img": "https://preview.redd.it/bz73jhca9w3f1.jpeg?auto=webp&s=3ec55a9a7386fd201f894f26da824f8b18356ed6"
    },
    {
        "id": "1kz5bd5",
        "title": "This is why I pay for the internet",
        "body": "",
        "numUpvotes": 16351,
        "dateCreated": "Fri May 30 2025 07:15:07 GMT-0700 (Pacific Daylight Time)",
        "upTime": 4,
        "subreddit": "BeAmazed",
        "subredditId": "t5_363r3",
        "author": "Mental-Dark4547",
        "comments": [],
        "img": "https://external-preview.redd.it/cnVzcXVxZjZneDNmMV1UEMknlQu12d_Z-F1TF39yx9tLlABUzfcyEnFChJGI.png?auto=webp&s=f70757758f52edde4f0c52e164c174faa8238a5a"
    },
    {
        "id": "1kz554s",
        "title": "Thom Yorke statement from instagram",
        "body": "",
        "numUpvotes": 12886,
        "dateCreated": "Fri May 30 2025 07:07:45 GMT-0700 (Pacific Daylight Time)",
        "upTime": 4,
        "subreddit": "radiohead",
        "subredditId": "t5_2r3p6",
        "author": "Ksherwood96",
        "comments": [],
        "img": ""
    },
    {
        "id": "1kz8rkb",
        "title": "But please dad 🙏",
        "body": "",
        "numUpvotes": 8285,
        "dateCreated": "Fri May 30 2025 09:33:26 GMT-0700 (Pacific Daylight Time)",
        "upTime": 2,
        "subreddit": "MadeMeSmile",
        "subredditId": "t5_2uqcm",
        "author": "Sad_Cow_577",
        "comments": [],
        "img": "https://external-preview.redd.it/c2tqZXNra2M1eTNmMWu8jf3A4-v7htOfLs71-BRhU3f4R8KaNSK7JminrwJa.png?format=pjpg&auto=webp&s=1ea21270a63702af3881dc9b4be73f13b6051714"
    },
    {
        "id": "1kyrqtz",
        "title": "Think your cat is a supermodel? Prove it—drop the pics!",
        "body": "How old is she?",
        "numUpvotes": 12199,
        "dateCreated": "Thu May 29 2025 18:19:23 GMT-0700 (Pacific Daylight Time)",
        "upTime": 17,
        "subreddit": "cats",
        "subredditId": "t5_2qhta",
        "author": "Liya_Yip",
        "comments": [],
        "img": "https://preview.redd.it/dhmvesiamt3f1.jpeg?auto=webp&s=cf5bde119fdbc349abc401703c3f3c2512b24745"
    },
    {
        "id": "1kz2om5",
        "title": "Trump says China violated its agreement with US",
        "body": "",
        "numUpvotes": 9007,
        "dateCreated": "Fri May 30 2025 05:14:20 GMT-0700 (Pacific Daylight Time)",
        "upTime": 6,
        "subreddit": "StockMarket",
        "subredditId": "t5_2qjuv",
        "author": "cxr_cxr2",
        "comments": [],
        "img": "https://preview.redd.it/hkxdrw55vw3f1.jpeg?auto=webp&s=b00792289bb2a06a7ad7d712454a37bee5c202e6"
    },
    {
        "id": "1kypu65",
        "title": "🌸💖After 15 Years of Homelessness, I Finally Have My Own Home!🌸💖",
        "body": "",
        "numUpvotes": 110294,
        "dateCreated": "Thu May 29 2025 16:46:16 GMT-0700 (Pacific Daylight Time)",
        "upTime": 19,
        "subreddit": "MadeMeSmile",
        "subredditId": "t5_2uqcm",
        "author": "Bunklsd",
        "comments": [],
        "img": ""
    },
    {
        "id": "1kz9eo4",
        "title": "Unconstitutionality of Georgia Abortion Ban",
        "body": "",
        "numUpvotes": 7103,
        "dateCreated": "Fri May 30 2025 09:58:53 GMT-0700 (Pacific Daylight Time)",
        "upTime": 1,
        "subreddit": "MurderedByWords",
        "subredditId": "t5_3hx3r",
        "author": "smellyshartAAA",
        "comments": [],
        "img": "https://preview.redd.it/g8e6pcuw9y3f1.jpeg?auto=webp&s=52e19a39756a54623e0cf7a5ac2dcfb94383a362"
    },
    {
        "id": "1kz6mgx",
        "title": "No way you guys didn't have this yet",
        "body": "",
        "numUpvotes": 13017,
        "dateCreated": "Fri May 30 2025 08:08:16 GMT-0700 (Pacific Daylight Time)",
        "upTime": 3,
        "subreddit": "memes",
        "subredditId": "t5_2qjpg",
        "author": "Satokibi",
        "comments": [],
        "img": "https://preview.redd.it/axocjldwpx3f1.gif?format=png8&s=a57bd36a16582c4834974584014e4f9fea39886b"
    },
    {
        "id": "1kz6zer",
        "title": "NBA star Zion Williamson accused of rape",
        "body": "https://www.wdsu.com/article/new-orleans-pelicans-zion-williamson-rape-allegations/64928591\n\n> Court documents detail that the woman, who is unnamed, outlined allegations of an abusive relationship with Williamson from 2018 until 2023.\n\n> The woman alleges multiple instances of rape, strangulation, and domestic violence.\n\n> The woman also outlined in the court filing accusations of strangulation, death threats to her and her family, and physical abuse involving being kicked, being slammed with a car door, and suffocation until she lost consciousness.\n\n> According to court documents, the woman said the sexual assaults, abuse, and rapes continued to happen in California, Louisiana, and Texas until their relationship ended in 2023.",
        "numUpvotes": 7476,
        "dateCreated": "Fri May 30 2025 08:22:43 GMT-0700 (Pacific Daylight Time)",
        "upTime": 3,
        "subreddit": "nba",
        "subredditId": "t5_2qo4s",
        "author": "The_Blind_Bomber",
        "comments": [],
        "img": "https://external-preview.redd.it/-ZMQO2MnA61AVLHe7AsNiUZYpNMwFNn7Dt0gJ5TVskM.jpg?auto=webp&s=f7c3b116e40033e0d4b4bfd867e6b078d43f196a"
    },
    {
        "id": "1kz9i0k",
        "title": "Cow brings baby over to show it off to her owner",
        "body": "",
        "numUpvotes": 6959,
        "dateCreated": "Fri May 30 2025 10:02:21 GMT-0700 (Pacific Daylight Time)",
        "upTime": 1,
        "subreddit": "aww",
        "subredditId": "t5_2qh1o",
        "author": "Midnight_Sick",
        "comments": [],
        "img": "https://external-preview.redd.it/NXF1anMxcGhheTNmMdRH8CMgQb30iEuNc1tposYkmSfCcN1vnHtBTITmmpZ6.png?format=pjpg&auto=webp&s=63f88a85a5940155a0ff8415cefeeffe1b7449d4"
    },
    {
        "id": "1kyz89h",
        "title": "She always called me “just the boyfriend,” so I helped her move, quietly.",
        "body": "My girlfriend’s sister never liked me. Every time we were around family, she’d say stuff like, “you’re just her boyfriend, not family” or “don’t get too comfortable.” I let it slide for over a year because I didn’t want to start drama. A few months ago, she needed help moving apartments. Nobody else was free, and she asked me. I said sure, showed up early, loaded the truck, even brought her a coffee. She was kinda shocked. When we finished, she just looked at me and said, “I didn’t think you’d actually show.” I just smiled and said, “yeah I’m just the boyfriend of your sister, remember?” she stared at me for a second and act like guilty. \n\nShe’s been way more respectful since.",
        "numUpvotes": 54849,
        "dateCreated": "Fri May 30 2025 01:43:56 GMT-0700 (Pacific Daylight Time)",
        "upTime": 10,
        "subreddit": "pettyrevenge",
        "subredditId": "t5_2vg7t",
        "author": "Initial-Afternoon532",
        "comments": [],
        "img": ""
    }
]