export const mockData = [
    {
        "id": "1kz5xgo",
        "title": "This is how plants breathe: a microscopic close-up of a single stoma on a boat lily leaf.",
        "body": "",
        "numUpvotes": 25109,
        "dateCreated": "Fri May 30 2025 07:40:16 GMT-0700 (Pacific Daylight Time)",
        "upTime": 4,
        "subreddit": "Damnthatsinteresting",
        "subredditId": "t5_2xxyj",
        "author": "TRIPYXEN",
        "comments": [],
        "img": "https://external-preview.redd.it/eDUxc3FqY3preDNmMVRooBfPateepzDsarKrvXSx5EsNtzJyhch4WaMHL2cU.png?format=pjpg&auto=webp&s=8b80c096f0f15a1864093b7f6d6bc4e8c1af2134"
    },
    {
        "id": "1kyyvgd",
        "title": "Name the game that got you like this",
        "body": "",
        "numUpvotes": 28043,
        "dateCreated": "Fri May 30 2025 01:18:17 GMT-0700 (Pacific Daylight Time)",
        "upTime": 10,
        "subreddit": "Steam",
        "subredditId": "t5_2qwis",
        "author": "bijelo123",
        "comments": [],
        "img": "https://preview.redd.it/w2re7q71pv3f1.jpeg?auto=webp&s=937d13b6d6a05585166a0330a0dd330b3e5a7f19"
    },
    {
        "id": "1kyydm2",
        "title": "Draw a B on your keyboard.Let's see what autocorrect is up to.",
        "body": "",
        "numUpvotes": 2472,
        "dateCreated": "Fri May 30 2025 00:43:07 GMT-0700 (Pacific Daylight Time)",
        "upTime": 11,
        "subreddit": "teenagers",
        "subredditId": "t5_2rjli",
        "author": "Stunning-Weakness257",
        "comments": [],
        "img": "https://preview.redd.it/fiye3l9riv3f1.jpeg?auto=webp&s=c45aaca5f68494186dffaad40c02c3f69a83ce49"
    },
    {
        "id": "1kz762l",
        "title": "Taylor has gained back the rights to all of her music again",
        "body": "I mean the kind of achievement that would secure Taylor's legend status in the future. Anything about her touring success, streaming success, selling success, cutural impact, critical acclaim… can be considered. Is it her 4th win for Album of The Year at Grammy? Is it “The Eras Tour” — the highest grossing tour of all time? Or anything else?",
        "numUpvotes": 15658,
        "dateCreated": "Fri May 30 2025 08:30:09 GMT-0700 (Pacific Daylight Time)",
        "upTime": 3,
        "subreddit": "TaylorSwift",
        "subredditId": "t5_2rlwe",
        "author": "maydeletelater",
        "comments": [],
        "img": ""
    },
    {
        "id": "1kypj8h",
        "title": "The Asshole escaped outside and bit me when I got him back in",
        "body": "",
        "numUpvotes": 49339,
        "dateCreated": "Thu May 29 2025 16:31:39 GMT-0700 (Pacific Daylight Time)",
        "upTime": 19,
        "subreddit": "CatsAreAssholes",
        "subredditId": "t5_2zexl",
        "author": "AzraelKhaine",
        "comments": [],
        "img": ""
    },
    {
        "id": "1kz0vxp",
        "title": "What's The Best Movie That You're Sure 90% Of This Sub Hasn't Seen?",
        "body": "Looking for some underrated films! \n\nMy personal pick is \"Coherence\" (2013). One of the films that blows your mind once you realize what's happening. Even more impressive that it was shot in 5 nights with no script (about 80% of the dialogue is ad-libbed) which makes the whole movie even more grounded and realistic. Phenomenal film, and go watch it as blindly as you can, its a one of a kind experience.",
        "numUpvotes": 2874,
        "dateCreated": "Fri May 30 2025 03:33:09 GMT-0700 (Pacific Daylight Time)",
        "upTime": 8,
        "subreddit": "movies",
        "subredditId": "t5_2qh3s",
        "author": "Rhye5",
        "comments": [],
        "img": ""
    },
    {
        "id": "1kz0kbw",
        "title": "[OC] WORLDWIDE GIVEAWAY! Enter for a chance to win a FAFNIR DICE VAULT![MOD APPROVED]",
        "body": "Limited time **DISCOUNT CODE**! Use code '**REDDIT3**' when buying a Dice Vault or a set of dice from my website for **10% off!** This code is good for a week. [www.magnicraftworks.com](https://magnicraftworks.com/) We add new dice sets weekly!",
        "numUpvotes": 2813,
        "dateCreated": "Fri May 30 2025 03:12:46 GMT-0700 (Pacific Daylight Time)",
        "upTime": 8,
        "subreddit": "DnD",
        "subredditId": "t5_2r9ei",
        "author": "120mmfilms",
        "comments": [],
        "img": "https://preview.redd.it/bz73jhca9w3f1.jpeg?auto=webp&s=3ec55a9a7386fd201f894f26da824f8b18356ed6"
    }
]